### ISSUE TITLE
Epic - Security

### ISSUE THREAD

**Issue by AdiKuwar37** [adikuwar-org/api-service#26]
Acceptance Criteria
- [x] https://github.com/adikuwar-org/api-service/issues/32
- [x] https://github.com/adikuwar-org/api-service/issues/33
- [x] https://github.com/adikuwar-org/api-service/issues/27
- [x] https://github.com/adikuwar-org/api-service/issues/28
- [x] https://github.com/adikuwar-org/api-service/issues/29
- [x] https://github.com/adikuwar-org/api-service/issues/30
- [x] https://github.com/adikuwar-org/api-service/issues/31

**Comment by AdiKuwar37** [comment]
All stories in this epic are completed.
